config/routes.rb
Rails.application.routes.draw do
 resources :users
 root to: 'controller_s#home'
 get '/show', to: 'users#show'
 get 'auth/:provider/callback', to: 'sessions#create'
 get 'signout', to: 'sessions#destroy', as: 'signout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploaders :images, AvatarUploader
  serialize :images, JSON
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first || create_from_omniauth(auth)
  end
  
  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"] || auth["info"]["nickname"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/controller_s_controller.rb
class ControllerSController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 def create
   user = User.from_omniauth(request.env['omniauth.auth'])
   session[:user_id] = user.id
   redirect_to root_url
   flash.now[:success] = "Welcome to the Sample App!"
 end
 
   def destroy
     log_out
     redirect_to root_url
   end
   
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      #redirect_to show_path
      redirect_to root_url
    else
      render 'edit'
    end
  end
  
  def user_params
      params.require(:user).permit({images: []}, :remove_images)
  end
  
  def show
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controller_s_helper.rb
module ControllerSHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def current_user
  @current_user ||= User.find_by(id: session[:user_id])
end

def logged_in?
  !current_user.nil?
end

def log_out
  session.delete(:user_id)
  @current_user = nil
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/controller_s/help.html.erb
<h1>ControllerS#help</h1>
<p>Find me in app/views/controller_s/help.html.erb</p>

app/views/controller_s/home.html.erb
<h1>ControllerS#home</h1>

<p>Find me in app/views/controller_s/home.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% if logged_in? %>
    <%= link_to "Settings", edit_user_path(current_user) %>
      Signed in as, <%= current_user.name%>
      <%= link_to "Sign out", signout_path %>
      <% else %>
      <%= link_to "Sign in with vkontakte", "auth/vkontakte" %>
      <%= link_to "Sign in with github", "auth/github" %>
      <% end %>
      
      
      
  </body>
</html>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

  <%= form_for @user, html: { multipart: true } do |f| %>
    <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.file_field :images, multiple: true %>
        <%= f.submit "Сохранить"%>
          <% @user.images.each do |image| %>
           <li><%= image_tag image.url(:thumb) %></li>
           <%= f.check_box :remove_images %>
           Remove image
          <% end %>
          <p>
          <!--<%= @user.attributes %>-->
          
       
          </p>
    </p>
  <% end %> 

app/views/users/show.html.erb
<%= params.require(:user).permit({images: []}, :remove_images) %>